#!/usr/bin/env python3
"""
Derive the IDENTITY-LINK m=1 discrete-EGPD (DEGPD model 1) negative log-likelihood
gradient and Hessian, for use in src/degpd.cpp functions degpd1id0 / degpd1id12.

Unlike the existing degpd1d12 (parameterised in lxi = log(xi), so xi>0), here the
shape xi uses an IDENTITY link: parameters are (lsigma, xi, lkappa) with xi real
(may be negative -> bounded/short tail, finite upper endpoint -sigma/xi).

Model 1 discrete EGPD, X = floor(Y), Y ~ EGPD1:
  sigma = exp(lsigma),  kappa = exp(lkappa)
  H(t)  = 1 - (1 + xi*t/sigma)^(-1/xi)         (GPD CDF; identity xi)
  F(t)  = H(t)^kappa                            (EGPD1 CDF)
  P(X=y)= F(y+1) - F(y)
  nll   = -log(F(y+1) - F(y))

Outputs:
  - C++ CSE fragments for d0 (nll) and d12 (3 grad + 6 upper-tri Hessian) to
    derive_degpd1_identity.cpp.txt
  - a numeric self-check: analytic grad/Hessian vs sympy numeric finite diff.
Column order (matches degpd1d12 / .bounded_xi_chain):
  out0=d/dlsigma out1=d/dxi out2=d/dlkappa
  out3=d2/dlsigma2 out4=d2/dlsigma dxi out5=d2/dlsigma dlkappa
  out6=d2/dxi2 out7=d2/dxi dlkappa out8=d2/dlkappa2
"""
import sympy as sp
from sympy import symbols, exp, log, cse, Symbol
try:
    from sympy import ccode
except ImportError:
    from sympy.printing.c import ccode

y, lsigma, xi, lkappa = symbols('y lsigma xi lkappa', real=True)
sigma = exp(lsigma)
kappa = exp(lkappa)

def H(t):
    return 1 - (1 + xi*t/sigma)**(-1/xi)
def F(t):
    return H(t)**kappa

P   = F(y+1) - F(y)
nll = -log(P)

params = [lsigma, xi, lkappa]
grad = [sp.diff(nll, p) for p in params]
hess = []
for i in range(3):
    for j in range(i, 3):
        hess.append(sp.diff(nll, params[i], params[j]))
exprs = grad + hess  # 9 outputs in the required column order

# ---- numeric self-check: analytic vs central finite difference ----
import random
random.seed(0)
def fnum(expr, vals):
    return float(expr.subs(vals).evalf())
maxerr = 0.0
for _ in range(200):
    yv = random.randint(0, 6)
    sv = random.uniform(-1.0, 2.0)      # lsigma
    xv = random.uniform(-0.45, 0.35)    # xi spanning negative & positive
    kv = random.uniform(-0.5, 1.0)      # lkappa
    # keep observation inside support: need 1+xi*(y+1)/sigma>0
    if 1 + xv*(yv+1)/float(sp.exp(sv)) <= 0.05:
        continue
    vals = {y: yv, lsigma: sv, xi: xv, lkappa: kv}
    h = 1e-5
    for k, p in enumerate(params):
        vp = dict(vals); vp[p] = vals[p] + h
        vm = dict(vals); vm[p] = vals[p] - h
        fd = (fnum(nll, vp) - fnum(nll, vm)) / (2*h)
        an = fnum(grad[k], vals)
        maxerr = max(maxerr, abs(fd - an))
print(f"# self-check max |analytic grad - FD| over 200 random pts: {maxerr:.3e}")

# ---- emit C++ CSE fragments ----
repl, reduced = cse(exprs, optimizations='basic')
out = []
out.append("// ==== AUTO-GENERATED by derive_degpd1_identity.py ====")
out.append("// identity-link m=1 DEGPD: params (lsigma, xi, lkappa); xi real.")
out.append("// CSE temporaries:")
for sym, e in repl:
    out.append(f"double {sym} = {ccode(e)};")
out.append("// outputs (column order: g_lsigma,g_xi,g_lkappa, h_ss,h_sx,h_sk,h_xx,h_xk,h_kk):")
for i, e in enumerate(reduced):
    out.append(f"OUT{i} = {ccode(e)};")
txt = "\n".join(out)
with open("derive_degpd1_identity.cpp.txt", "w") as fh:
    fh.write(txt + "\n")
print(f"# wrote derive_degpd1_identity.cpp.txt  ({len(repl)} temporaries, {len(reduced)} outputs)")
