// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// degpd1d0
double degpd1d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_degpd1d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(degpd1d0(pars, X1, X2, X3, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// degpd1d12
arma::mat degpd1d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, const arma::uvec dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_degpd1d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(degpd1d12(pars, X1, X2, X3, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// degpd2d0
double degpd2d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, const arma::mat& X5, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_degpd2d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(degpd2d0(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// degpd2d12
arma::mat degpd2d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::mat X5, arma::vec yvec, const arma::uvec dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_degpd2d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(degpd2d12(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// degpd3d0
double degpd3d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_degpd3d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(degpd3d0(pars, X1, X2, X3, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// degpd3d12
arma::mat degpd3d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, const arma::uvec dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_degpd3d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(degpd3d12(pars, X1, X2, X3, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// degpd4d0
double degpd4d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_degpd4d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(degpd4d0(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// degpd4d12
arma::mat degpd4d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::vec yvec, const arma::uvec dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_degpd4d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(degpd4d12(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// egpd1d0
double egpd1d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_egpd1d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd1d0(pars, X1, X2, X3, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// egpd1d12
arma::mat egpd1d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, const arma::uvec dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_egpd1d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd1d12(pars, X1, X2, X3, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// egpd1d34
arma::mat egpd1d34(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, const arma::uvec dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_egpd1d34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd1d34(pars, X1, X2, X3, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// egpd2d0
double egpd2d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, const arma::mat& X5, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_egpd2d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd2d0(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// egpd2d12
arma::mat egpd2d12(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, const arma::mat& X5, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_egpd2d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd2d12(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// egpd2d34
arma::mat egpd2d34(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, const arma::mat& X5, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_egpd2d34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd2d34(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// egpd3d0
double egpd3d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_egpd3d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd3d0(pars, X1, X2, X3, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// egpd3d12
arma::mat egpd3d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, const arma::uvec dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_egpd3d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd3d12(pars, X1, X2, X3, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// egpd3d34
arma::mat egpd3d34(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, const arma::uvec dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_egpd3d34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd3d34(pars, X1, X2, X3, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// egpd4d0
double egpd4d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_egpd4d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd4d0(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// egpd4d12
arma::mat egpd4d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::vec yvec, const arma::uvec dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_egpd4d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd4d12(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// egpd4d34
arma::mat egpd4d34(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::vec yvec, const arma::uvec dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_egpd4d34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd4d34(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// armapinv
arma::mat armapinv(arma::mat x, double tol);
RcppExport SEXP _egpd_armapinv(SEXP xSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(armapinv(x, tol));
    return rcpp_result_gen;
END_RCPP
}
// armaginv
arma::mat armaginv(arma::mat x, double tol);
RcppExport SEXP _egpd_armaginv(SEXP xSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(armaginv(x, tol));
    return rcpp_result_gen;
END_RCPP
}
// gH1
Rcpp::List gH1(arma::mat gh, arma::mat X1, const arma::uvec dupid, int dcate, int sand, int deriv);
RcppExport SEXP _egpd_gH1(SEXP ghSEXP, SEXP X1SEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP sandSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gh(ghSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type sand(sandSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(gH1(gh, X1, dupid, dcate, sand, deriv));
    return rcpp_result_gen;
END_RCPP
}
// gH2
Rcpp::List gH2(arma::mat gh, arma::mat X1, arma::mat X2, const arma::uvec dupid, int dcate, int sand, int deriv);
RcppExport SEXP _egpd_gH2(SEXP ghSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP sandSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gh(ghSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type sand(sandSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(gH2(gh, X1, X2, dupid, dcate, sand, deriv));
    return rcpp_result_gen;
END_RCPP
}
// gH3
Rcpp::List gH3(arma::mat gh, arma::mat X1, arma::mat X2, arma::mat X3, const arma::uvec dupid, int dcate, int sand, int deriv);
RcppExport SEXP _egpd_gH3(SEXP ghSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP sandSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gh(ghSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type sand(sandSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(gH3(gh, X1, X2, X3, dupid, dcate, sand, deriv));
    return rcpp_result_gen;
END_RCPP
}
// gH4
Rcpp::List gH4(arma::mat gh, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, const arma::uvec dupid, int dcate, int sand, int deriv);
RcppExport SEXP _egpd_gH4(SEXP ghSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP sandSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gh(ghSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type sand(sandSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(gH4(gh, X1, X2, X3, X4, dupid, dcate, sand, deriv));
    return rcpp_result_gen;
END_RCPP
}
// gH5
Rcpp::List gH5(arma::mat gh, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::mat X5, const arma::uvec dupid, int dcate, int sand, int deriv);
RcppExport SEXP _egpd_gH5(SEXP ghSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP sandSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gh(ghSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type sand(sandSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(gH5(gh, X1, X2, X3, X4, X5, dupid, dcate, sand, deriv));
    return rcpp_result_gen;
END_RCPP
}
// gH6
Rcpp::List gH6(arma::mat gh, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::mat X5, arma::mat X6, const arma::uvec dupid, int dcate, int sand, int deriv);
RcppExport SEXP _egpd_gH6(SEXP ghSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP X6SEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP sandSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gh(ghSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X6(X6SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type sand(sandSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(gH6(gh, X1, X2, X3, X4, X5, X6, dupid, dcate, sand, deriv));
    return rcpp_result_gen;
END_RCPP
}
// zidegpd1d0
double zidegpd1d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_zidegpd1d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(zidegpd1d0(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// zidegpd1d12
arma::mat zidegpd1d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_zidegpd1d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(zidegpd1d12(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// zidegpd2d0
double zidegpd2d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, const arma::mat& X5, const arma::mat& X6, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_zidegpd2d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP X6SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X6(X6SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(zidegpd2d0(pars, X1, X2, X3, X4, X5, X6, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// zidegpd2d12
arma::mat zidegpd2d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::mat X5, arma::mat X6, arma::vec yvec, const arma::uvec dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_zidegpd2d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP X6SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X6(X6SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(zidegpd2d12(pars, X1, X2, X3, X4, X5, X6, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// zidegpd3d0
double zidegpd3d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_zidegpd3d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(zidegpd3d0(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// zidegpd3d12
arma::mat zidegpd3d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::vec yvec, const arma::uvec dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_zidegpd3d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(zidegpd3d12(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// zidegpd4d0
double zidegpd4d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, const arma::mat& X5, arma::vec yvec, const arma::uvec& dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_zidegpd4d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(zidegpd4d0(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}
// zidegpd4d12
arma::mat zidegpd4d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::mat X5, arma::vec yvec, const arma::uvec dupid, int dcate, const Rcpp::List& offsets);
RcppExport SEXP _egpd_zidegpd4d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP offsetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type offsets(offsetsSEXP);
    rcpp_result_gen = Rcpp::wrap(zidegpd4d12(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_egpd_degpd1d0", (DL_FUNC) &_egpd_degpd1d0, 8},
    {"_egpd_degpd1d12", (DL_FUNC) &_egpd_degpd1d12, 8},
    {"_egpd_degpd2d0", (DL_FUNC) &_egpd_degpd2d0, 10},
    {"_egpd_degpd2d12", (DL_FUNC) &_egpd_degpd2d12, 10},
    {"_egpd_degpd3d0", (DL_FUNC) &_egpd_degpd3d0, 8},
    {"_egpd_degpd3d12", (DL_FUNC) &_egpd_degpd3d12, 8},
    {"_egpd_degpd4d0", (DL_FUNC) &_egpd_degpd4d0, 9},
    {"_egpd_degpd4d12", (DL_FUNC) &_egpd_degpd4d12, 9},
    {"_egpd_egpd1d0", (DL_FUNC) &_egpd_egpd1d0, 8},
    {"_egpd_egpd1d12", (DL_FUNC) &_egpd_egpd1d12, 8},
    {"_egpd_egpd1d34", (DL_FUNC) &_egpd_egpd1d34, 8},
    {"_egpd_egpd2d0", (DL_FUNC) &_egpd_egpd2d0, 10},
    {"_egpd_egpd2d12", (DL_FUNC) &_egpd_egpd2d12, 10},
    {"_egpd_egpd2d34", (DL_FUNC) &_egpd_egpd2d34, 10},
    {"_egpd_egpd3d0", (DL_FUNC) &_egpd_egpd3d0, 8},
    {"_egpd_egpd3d12", (DL_FUNC) &_egpd_egpd3d12, 8},
    {"_egpd_egpd3d34", (DL_FUNC) &_egpd_egpd3d34, 8},
    {"_egpd_egpd4d0", (DL_FUNC) &_egpd_egpd4d0, 9},
    {"_egpd_egpd4d12", (DL_FUNC) &_egpd_egpd4d12, 9},
    {"_egpd_egpd4d34", (DL_FUNC) &_egpd_egpd4d34, 9},
    {"_egpd_armapinv", (DL_FUNC) &_egpd_armapinv, 2},
    {"_egpd_armaginv", (DL_FUNC) &_egpd_armaginv, 2},
    {"_egpd_gH1", (DL_FUNC) &_egpd_gH1, 6},
    {"_egpd_gH2", (DL_FUNC) &_egpd_gH2, 7},
    {"_egpd_gH3", (DL_FUNC) &_egpd_gH3, 8},
    {"_egpd_gH4", (DL_FUNC) &_egpd_gH4, 9},
    {"_egpd_gH5", (DL_FUNC) &_egpd_gH5, 10},
    {"_egpd_gH6", (DL_FUNC) &_egpd_gH6, 11},
    {"_egpd_zidegpd1d0", (DL_FUNC) &_egpd_zidegpd1d0, 9},
    {"_egpd_zidegpd1d12", (DL_FUNC) &_egpd_zidegpd1d12, 9},
    {"_egpd_zidegpd2d0", (DL_FUNC) &_egpd_zidegpd2d0, 11},
    {"_egpd_zidegpd2d12", (DL_FUNC) &_egpd_zidegpd2d12, 11},
    {"_egpd_zidegpd3d0", (DL_FUNC) &_egpd_zidegpd3d0, 9},
    {"_egpd_zidegpd3d12", (DL_FUNC) &_egpd_zidegpd3d12, 9},
    {"_egpd_zidegpd4d0", (DL_FUNC) &_egpd_zidegpd4d0, 10},
    {"_egpd_zidegpd4d12", (DL_FUNC) &_egpd_zidegpd4d12, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_egpd(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
