# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bell1d0 <- function(pars, X1, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_bell1d0`, pars, X1, yvec, dupid, dcate, offsets)
}

bell1d12 <- function(pars, X1, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_bell1d12`, pars, X1, yvec, dupid, dcate, offsets)
}

bellnat1d0 <- function(pars, X1, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_bellnat1d0`, pars, X1, yvec, dupid, dcate, offsets)
}

bellnat1d12 <- function(pars, X1, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_bellnat1d12`, pars, X1, yvec, dupid, dcate, offsets)
}

zibell1d0 <- function(pars, X1, X2, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zibell1d0`, pars, X1, X2, yvec, dupid, dcate, offsets)
}

zibell1d12 <- function(pars, X1, X2, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zibell1d12`, pars, X1, X2, yvec, dupid, dcate, offsets)
}

zibellnat1d0 <- function(pars, X1, X2, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zibellnat1d0`, pars, X1, X2, yvec, dupid, dcate, offsets)
}

zibellnat1d12 <- function(pars, X1, X2, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zibellnat1d12`, pars, X1, X2, yvec, dupid, dcate, offsets)
}

bell_pmf_cpp <- function(n, theta) {
    .Call(`_egpd_bell_pmf_cpp`, n, theta)
}

bell_W0_cpp <- function(x) {
    .Call(`_egpd_bell_W0_cpp`, x)
}

cmp1d0 <- function(pars, X1, X2, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_cmp1d0`, pars, X1, X2, yvec, dupid, dcate, offsets)
}

cmp1d12 <- function(pars, X1, X2, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_cmp1d12`, pars, X1, X2, yvec, dupid, dcate, offsets)
}

cmp_sums_cpp <- function(loglambda, nu) {
    .Call(`_egpd_cmp_sums_cpp`, loglambda, nu)
}

cmp_ll_from_mu_cpp <- function(mu, nu) {
    .Call(`_egpd_cmp_ll_from_mu_cpp`, mu, nu)
}

cmp_logpmf_cpp <- function(y, mu, nu) {
    .Call(`_egpd_cmp_logpmf_cpp`, y, mu, nu)
}

cmp_grad_cpp <- function(y, mu, nu) {
    .Call(`_egpd_cmp_grad_cpp`, y, mu, nu)
}

cmp_bounds_cpp <- function() {
    .Call(`_egpd_cmp_bounds_cpp`)
}

gpois1d0 <- function(pars, X1, X2, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_gpois1d0`, pars, X1, X2, yvec, dupid, dcate, offsets)
}

gpois1d12 <- function(pars, X1, X2, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_gpois1d12`, pars, X1, X2, yvec, dupid, dcate, offsets)
}

gwaring1d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_gwaring1d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

gwaring1d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_gwaring1d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

plnorm1d0 <- function(pars, X1, X2, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_plnorm1d0`, pars, X1, X2, yvec, dupid, dcate, offsets)
}

plnorm1d12 <- function(pars, X1, X2, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_plnorm1d12`, pars, X1, X2, yvec, dupid, dcate, offsets)
}

gpois_logpmf_cpp <- function(y, mu, lambda) {
    .Call(`_egpd_gpois_logpmf_cpp`, y, mu, lambda)
}

gwaring_logpmf_cpp <- function(y, mu, k, rho) {
    .Call(`_egpd_gwaring_logpmf_cpp`, y, mu, k, rho)
}

plnorm_logpmf_cpp <- function(y, mu, sigma) {
    .Call(`_egpd_plnorm_logpmf_cpp`, y, mu, sigma)
}

cf_bounds_cpp <- function() {
    .Call(`_egpd_cf_bounds_cpp`)
}

cf_grad_cpp <- function(fam, y, eta) {
    .Call(`_egpd_cf_grad_cpp`, fam, y, eta)
}

degpd1d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max) {
    .Call(`_egpd_degpd1d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max)
}

degpd1d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max) {
    .Call(`_egpd_degpd1d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max)
}

degpd2d0 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets, xi_max, xi_identity = FALSE) {
    .Call(`_egpd_degpd2d0`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets, xi_max, xi_identity)
}

degpd2d12 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets, xi_max, xi_identity = FALSE) {
    .Call(`_egpd_degpd2d12`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets, xi_max, xi_identity)
}

degpd3d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max, xi_identity = FALSE) {
    .Call(`_egpd_degpd3d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max, xi_identity)
}

degpd3d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max, xi_identity = FALSE) {
    .Call(`_egpd_degpd3d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max, xi_identity)
}

degpd4d0 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets, xi_max, xi_identity = FALSE) {
    .Call(`_egpd_degpd4d0`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets, xi_max, xi_identity)
}

degpd4d12 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets, xi_max, xi_identity = FALSE) {
    .Call(`_egpd_degpd4d12`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets, xi_max, xi_identity)
}

degpd5d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max, xi_identity = FALSE) {
    .Call(`_egpd_degpd5d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max, xi_identity)
}

degpd5d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max, xi_identity = FALSE) {
    .Call(`_egpd_degpd5d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max, xi_identity)
}

degpd6d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max, xi_identity = FALSE) {
    .Call(`_egpd_degpd6d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max, xi_identity)
}

degpd6d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max, xi_identity = FALSE) {
    .Call(`_egpd_degpd6d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max, xi_identity)
}

degpd1id0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max) {
    .Call(`_egpd_degpd1id0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max)
}

degpd1id12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max) {
    .Call(`_egpd_degpd1id12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets, xi_max)
}

egpd1d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd1d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd1d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd1d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd1d34 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd1d34`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd2d0 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd2d0`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets)
}

egpd2d12 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd2d12`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets)
}

egpd2d34 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd2d34`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets)
}

egpd3d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd3d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd3d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd3d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd3d34 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd3d34`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd4d0 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd4d0`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

egpd4d12 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd4d12`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

egpd4d34 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd4d34`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

egpd5d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd5d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd5d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd5d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd6d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd6d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd6d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd6d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

armapinv <- function(x, tol) {
    .Call(`_egpd_armapinv`, x, tol)
}

armaginv <- function(x, tol) {
    .Call(`_egpd_armaginv`, x, tol)
}

gpig_set_opts <- function(method, yswitch, order, eps, sptol, ymax, nquad, normalize) {
    invisible(.Call(`_egpd_gpig_set_opts`, method, yswitch, order, eps, sptol, ymax, nquad, normalize))
}

gpig_get_opts <- function() {
    .Call(`_egpd_gpig_get_opts`)
}

gpig_logS_cpp <- function(a, b, c) {
    .Call(`_egpd_gpig_logS_cpp`, a, b, c)
}

gpig_logp_cpp <- function(y, a, b, c) {
    .Call(`_egpd_gpig_logp_cpp`, y, a, b, c)
}

gpig1d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_gpig1d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

gpig1d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_gpig1d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

gpignat1d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_gpignat1d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

gpignat1d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_gpignat1d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

zigpig1d0 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zigpig1d0`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zigpig1d12 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zigpig1d12`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zigpignat1d0 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zigpignat1d0`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zigpignat1d12 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zigpignat1d12`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

gpig_pmf_cpp <- function(n, a, b, c) {
    .Call(`_egpd_gpig_pmf_cpp`, n, a, b, c)
}

.gH1 <- function(gh, X1, dupid, dcate, sand, deriv) {
    .Call(`_egpd_gH1`, gh, X1, dupid, dcate, sand, deriv)
}

.gH2 <- function(gh, X1, X2, dupid, dcate, sand, deriv) {
    .Call(`_egpd_gH2`, gh, X1, X2, dupid, dcate, sand, deriv)
}

.gH3 <- function(gh, X1, X2, X3, dupid, dcate, sand, deriv) {
    .Call(`_egpd_gH3`, gh, X1, X2, X3, dupid, dcate, sand, deriv)
}

.gH4 <- function(gh, X1, X2, X3, X4, dupid, dcate, sand, deriv) {
    .Call(`_egpd_gH4`, gh, X1, X2, X3, X4, dupid, dcate, sand, deriv)
}

.gH5 <- function(gh, X1, X2, X3, X4, X5, dupid, dcate, sand, deriv) {
    .Call(`_egpd_gH5`, gh, X1, X2, X3, X4, X5, dupid, dcate, sand, deriv)
}

.gH6 <- function(gh, X1, X2, X3, X4, X5, X6, dupid, dcate, sand, deriv) {
    .Call(`_egpd_gH6`, gh, X1, X2, X3, X4, X5, X6, dupid, dcate, sand, deriv)
}

pig1d0 <- function(pars, X1, X2, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_pig1d0`, pars, X1, X2, yvec, dupid, dcate, offsets)
}

pig1d12 <- function(pars, X1, X2, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_pig1d12`, pars, X1, X2, yvec, dupid, dcate, offsets)
}

zipig1d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zipig1d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

zipig1d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zipig1d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

prl1d0 <- function(pars, X1, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_prl1d0`, pars, X1, yvec, dupid, dcate, offsets)
}

prl1d12 <- function(pars, X1, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_prl1d12`, pars, X1, yvec, dupid, dcate, offsets)
}

prl_logpmf_cpp <- function(y, tau) {
    .Call(`_egpd_prl_logpmf_cpp`, y, tau)
}

prl_grad_cpp <- function(y, eta) {
    .Call(`_egpd_prl_grad_cpp`, y, eta)
}

prl_bounds_cpp <- function() {
    .Call(`_egpd_prl_bounds_cpp`)
}

zidegpd1d0 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd1d0`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zidegpd1d12 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd1d12`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zidegpd2d0 <- function(pars, X1, X2, X3, X4, X5, X6, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd2d0`, pars, X1, X2, X3, X4, X5, X6, yvec, dupid, dcate, offsets)
}

zidegpd2d12 <- function(pars, X1, X2, X3, X4, X5, X6, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd2d12`, pars, X1, X2, X3, X4, X5, X6, yvec, dupid, dcate, offsets)
}

zidegpd3d0 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd3d0`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zidegpd3d12 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd3d12`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zidegpd4d0 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd4d0`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets)
}

zidegpd4d12 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd4d12`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets)
}

zidegpd5d0 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd5d0`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zidegpd5d12 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd5d12`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zidegpd6d0 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd6d0`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zidegpd6d12 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd6d12`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

