# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

degpd1d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_degpd1d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

degpd1d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_degpd1d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

degpd2d0 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_degpd2d0`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets)
}

degpd2d12 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_degpd2d12`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets)
}

degpd3d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_degpd3d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

degpd3d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_degpd3d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

degpd4d0 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_degpd4d0`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

degpd4d12 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_degpd4d12`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

egpd1d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd1d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd1d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd1d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd1d34 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd1d34`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd2d0 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd2d0`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets)
}

egpd2d12 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd2d12`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets)
}

egpd2d34 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd2d34`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets)
}

egpd3d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd3d0`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd3d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd3d12`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd3d34 <- function(pars, X1, X2, X3, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd3d34`, pars, X1, X2, X3, yvec, dupid, dcate, offsets)
}

egpd4d0 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd4d0`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

egpd4d12 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd4d12`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

egpd4d34 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_egpd4d34`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

armapinv <- function(x, tol) {
    .Call(`_egpd_armapinv`, x, tol)
}

armaginv <- function(x, tol) {
    .Call(`_egpd_armaginv`, x, tol)
}

.gH1 <- function(gh, X1, dupid, dcate, sand, deriv) {
    .Call(`_egpd_gH1`, gh, X1, dupid, dcate, sand, deriv)
}

.gH2 <- function(gh, X1, X2, dupid, dcate, sand, deriv) {
    .Call(`_egpd_gH2`, gh, X1, X2, dupid, dcate, sand, deriv)
}

.gH3 <- function(gh, X1, X2, X3, dupid, dcate, sand, deriv) {
    .Call(`_egpd_gH3`, gh, X1, X2, X3, dupid, dcate, sand, deriv)
}

.gH4 <- function(gh, X1, X2, X3, X4, dupid, dcate, sand, deriv) {
    .Call(`_egpd_gH4`, gh, X1, X2, X3, X4, dupid, dcate, sand, deriv)
}

.gH5 <- function(gh, X1, X2, X3, X4, X5, dupid, dcate, sand, deriv) {
    .Call(`_egpd_gH5`, gh, X1, X2, X3, X4, X5, dupid, dcate, sand, deriv)
}

.gH6 <- function(gh, X1, X2, X3, X4, X5, X6, dupid, dcate, sand, deriv) {
    .Call(`_egpd_gH6`, gh, X1, X2, X3, X4, X5, X6, dupid, dcate, sand, deriv)
}

zidegpd1d0 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd1d0`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zidegpd1d12 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd1d12`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zidegpd2d0 <- function(pars, X1, X2, X3, X4, X5, X6, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd2d0`, pars, X1, X2, X3, X4, X5, X6, yvec, dupid, dcate, offsets)
}

zidegpd2d12 <- function(pars, X1, X2, X3, X4, X5, X6, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd2d12`, pars, X1, X2, X3, X4, X5, X6, yvec, dupid, dcate, offsets)
}

zidegpd3d0 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd3d0`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zidegpd3d12 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd3d12`, pars, X1, X2, X3, X4, yvec, dupid, dcate, offsets)
}

zidegpd4d0 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd4d0`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets)
}

zidegpd4d12 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets) {
    .Call(`_egpd_zidegpd4d12`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate, offsets)
}

